#!/bin/sh

# Set a backup repo upstream

if [ -z "$1" ]
then
  echo "Usage: `basename $0` <remote-for-backups>" >&2
  echo "Add a remote first:"
  echo "git remote add my-backup-server my-backup-server:/path/to/git-repo.git"
  echo "then:"
  echo "git backup my-backup-server"
  exit 1
fi

if [ ! -e .git/hooks/post-commit ] 
then
  cat > .git/hooks/post-commit << EOF
#!/bin/sh
#
# Post commit hook script to push a repository automatically.
#

exec git push --mirror $1
EOF

  echo ".git/hooks/post-commit successfully created." 
  chmod +x .git/hooks/post-commit
else
  echo ".git/hooks/post-commit already exists"
  echo "Rename it and run again to not lose original post-commit content, manually edit if needed."
fi
